-- MySQL Script generated by MySQL Workbench
-- Fri Jul 21 12:34:05 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema asignaciones
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema asignaciones
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `asignaciones` DEFAULT CHARACTER SET utf8 ;
USE `asignaciones` ;

-- -----------------------------------------------------
-- Table `asignaciones`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asignaciones`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `usuarioscol` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asignaciones`.`dojos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asignaciones`.`dojos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asignaciones`.`ninjas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asignaciones`.`ninjas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `age` INT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `dojo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ninjas_dojos_idx` (`dojo_id` ASC) VISIBLE,
  CONSTRAINT `fk_ninjas_dojos`
    FOREIGN KEY (`dojo_id`)
    REFERENCES `asignaciones`.`dojos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asignaciones`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asignaciones`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `usuarioscol` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asignaciones`.`libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asignaciones`.`libros` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `num_paginas` INT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asignaciones`.`favoritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asignaciones`.`favoritos` (
  `usuarios_id` INT NOT NULL,
  `libros_id` INT NOT NULL,
  PRIMARY KEY (`usuarios_id`, `libros_id`),
  INDEX `fk_usuarios_has_libros_libros1_idx` (`libros_id` ASC) VISIBLE,
  INDEX `fk_usuarios_has_libros_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_has_libros_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `asignaciones`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_libros_libros1`
    FOREIGN KEY (`libros_id`)
    REFERENCES `asignaciones`.`libros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
